/*6.	Razão do estoque (Ficha Kardex)

##### TABELAS ENVOLVIDAS  #####
# V_MATERIAL                  #    
# ESTOQUE_MOV              #    
###############################

*/
 -- SELECT * FROM MATERIAL_CUSTO
--SOLUCAO 1

  
  -- DECLARANDO VARIAVEIS
     
	 DECLARE @V_COD_EMP INT,
	         @V_COD_MAT INT,
			 @DATA_MIN DATE,
			 @DATA_MAX DATE,
			 @SALDO_INI DECIMAL(10,2),
			 @SALDO_FIM DECIMAL(10,2),
			 @MOV_SAIDA DECIMAL(10,2),
			 @MOV_ENTRADA DECIMAL(10,2);
	-- ATRIBUINDO VALORES
    SET @V_COD_EMP=2
	SET @V_COD_MAT=1
	SET @SALDO_INI=0
	SET @SALDO_FIM=0
	SET @MOV_ENTRADA=0
	SET @MOV_SAIDA=0

	--PEGAR DATA MIN E MAX

	SELECT  @DATA_MIN=MIN(A.DATA_MOV),@DATA_MAX=MAX(A.DATA_MOV)
	 FROM ESTOQUE_MOV A
	 WHERE A.COD_EMPRESA=@V_COD_EMP
	 AND A.COD_MAT=@V_COD_MAT

	 --SELECT @DATA_MIN,@DATA_MAX
	 --ESTRUTRA DE REPETICAO DA DATA INICIAL ATE DATA FIM
	 WHILE @DATA_MIN<=@DATA_MAX
	  BEGIN 
	  -- SELECT @DATA_MIN
	  --CALCULAR MOV ENTRADA
	  SELECT @MOV_ENTRADA=SUM(A.QTD)
	   FROM ESTOQUE_MOV A
	   WHERE A.TIP_MOV='E'
	   AND A.COD_EMPRESA=@V_COD_EMP
	   AND A.COD_MAT=@V_COD_MAT
	   AND YEAR(A.DATA_MOV)=YEAR(@DATA_MIN)
	   AND MONTH(A.DATA_MOV)=MONTH(@DATA_MIN)

	   --CALCULAR MOV SAIDA
	  SELECT @MOV_SAIDA=SUM(A.QTD)
	   FROM ESTOQUE_MOV A
	   WHERE A.TIP_MOV='S'
	   AND A.COD_EMPRESA=@V_COD_EMP
	   AND A.COD_MAT=@V_COD_MAT
	   AND YEAR(A.DATA_MOV)=YEAR(@DATA_MIN)
	   AND MONTH(A.DATA_MOV)=MONTH(@DATA_MIN)
	    --CALCULA SALDO FINAL
		  SET @SALDO_FIM=(ISNULL(@SALDO_INI,0)+ISNULL(@MOV_ENTRADA,0))-ISNULL(@MOV_SAIDA,0)
       --IMPRIMI RESULTADO
	   SELECT CONVERT(VARCHAR(7),@DATA_MIN,111)ANO_MES , ISNULL(@SALDO_INI,0) SALDO_INCIAL,ISNULL(@MOV_ENTRADA,0) ENTRADA,ISNULL(@MOV_SAIDA,0) SAIDA,ISNULL(@SALDO_FIM,0) SALDO_FINAL

	   --ACRESC 1 MES
	   SET @DATA_MIN=DATEADD(M,1,@DATA_MIN)
	   --CALCULA SALDO INICIAL
	   SET @SALDO_INI=ISNULL(@SALDO_FIM,0)

	  END