 /*7.	Títulos a pagar em aberto, atraso, adiantado,em atraso, no prazo

##### TABELAS ENVOLVIDAS  #####
#                             #    
# CONTAS_PAGAR                #    
# FORNECEDOR                    #    
#                             #    
###############################
*/
--SOLUCAO 1
--ATUALIZAR BASE, PAGAR ALGUNS DOCUMENTOS
SELECT *, (A.ID_DOC+ID_DOC_ORIG)%A.ID_FOR,
    CASE WHEN (A.ID_DOC+ID_DOC_ORIG)%A.ID_FOR=0 THEN A.DATA_VENC  
	     WHEN (A.ID_DOC+ID_DOC_ORIG)%A.ID_FOR=1 THEN DATEADD(D,3,A.DATA_VENC)
		 WHEN (A.ID_DOC+ID_DOC_ORIG)%A.ID_FOR=2 THEN DATEADD(D,-3,A.DATA_VENC)
		 ELSE NULL END DATA_PAGTO
	FROM CONTAS_PAGAR A;

--UPDATE PAGANDO TITULOS
  UPDATE CONTAS_PAGAR SET DATA_PAGTO= CASE WHEN (ID_DOC+ID_DOC_ORIG)%ID_FOR=0 THEN DATA_VENC  
	     WHEN (ID_DOC+ID_DOC_ORIG)%ID_FOR=1 THEN DATEADD(D,3,DATA_VENC)
		 WHEN (ID_DOC+ID_DOC_ORIG)%ID_FOR=2 THEN DATEADD(D,-3,DATA_VENC)
		 ELSE NULL END 
  WHERE 1=1;
--REGRAS PARA TITULO
  --DATA_VENC=DATA_PAGTO E DATA_PAGTO<> NULL ESCREVE PAGO NO PRAZO
  --DATA_VENC<DATA_PAGTO E DATA_PAGTO<> NULL ESCREVE PAGO EM ATRASO
  --DATA_VENC>DATA_PAGTO E DATA_PAGTO<> NULL ESCREVE PAGO ADIANTADO
  --DATA_PAGTO= NULL E DATA_VENC>=HOJE   ESCREVE ABERTO
  --DATA_PAGTO= NULL E DATA_VENC<HOJE   ABERTO EM ATRASO
 
 SELECT A.COD_EMPRESA,A.ID_DOC,A.ID_FOR,A.DATA_VENC,A.DATA_PAGTO,A.VALOR,
      CASE WHEN A.DATA_VENC=A.DATA_PAGTO AND A.DATA_PAGTO IS NOT NULL THEN 'PAGO NO PRAZO'
	       WHEN A.DATA_VENC<A.DATA_PAGTO AND A.DATA_PAGTO IS NOT NULL THEN 'PAGO EM ATRASO'
		   WHEN A.DATA_VENC>A.DATA_PAGTO AND A.DATA_PAGTO IS NOT NULL THEN 'PAGO ADIANTADO'
		   WHEN A.DATA_PAGTO IS NULL AND A.DATA_VENC>=GETDATE()  THEN 'ABERTO'
		   WHEN A.DATA_PAGTO IS NULL AND A.DATA_VENC<GETDATE()  THEN 'ABERTO EM ATRASO'
		    ELSE 'OUTROS' END SITUACAO
  FROM CONTAS_PAGAR A
  INNER JOIN FORNECEDORES B
  ON A.COD_EMPRESA=B.COD_EMPRESA
  AND A.ID_FOR=B.ID_FOR
  