 /*2.	Simular aumento de 9% para cada funcionário

##### TABELAS ENVOLVIDAS  #####
#                             #    
# SALARIO                     #    
# FUNCIONARIO                 #    
#                             #    
###############################
*/
--SOLUCAO 1
--SELECT * FROM SALARIO

SELECT A.COD_EMPRESA,A.MATRICULA, A.NOME, SALARIO AS SALARIO_ATUAL, SALARIO*1.09 NOVO_SALARIO
 FROM FUNCIONARIO A
    INNER JOIN SALARIO B
	ON A.COD_EMPRESA=B.COD_EMPRESA
	AND A.MATRICULA=B.MATRICULA
	WHERE (A.DATE_DEMISS='1900-01-01' OR A.DATE_DEMISS IS NULL OR A.DATE_DEMISS='');


	--SOLUCAO 2 CRIAR PROC

	ALTER PROCEDURE PROC_SIMULA_AUMENTO (@V_PCT DECIMAL(10,2)) 

	AS

	DECLARE @V_PCT_TRATADO DECIMAL(10,2)

	SET @V_PCT_TRATADO=(@V_PCT/100)+1;

SELECT A.COD_EMPRESA,A.MATRICULA, A.NOME, SALARIO AS SALARIO_ATUAL, SALARIO*@V_PCT_TRATADO NOVO_SALARIO,(@V_PCT_TRATADO-1)*100 AS  PCT
 FROM FUNCIONARIO A
    INNER JOIN SALARIO B
	ON A.COD_EMPRESA=B.COD_EMPRESA
	AND A.MATRICULA=B.MATRICULA
	WHERE (A.DATE_DEMISS='1900-01-01' OR A.DATE_DEMISS IS NULL OR A.DATE_DEMISS='')

	RETURN

	--CHAMANDO A PROC

	EXEC PROC_SIMULA_AUMENTO 7