/*11.	Performance de vendas por Gerente

##### TABELAS ENVOLVIDAS  #####
#                             #   
# NOTA_FISCAL                 #   
# V_CANAL_VENDAS              #   
#                             #   
###############################

*/
--SOLUÇÃO 1
SELECT A.COD_EMPRESA,B.NOME_GER,SUM(A.TOTAL_NF) AS TOTAL 
  FROM NOTA_FISCAL A
  INNER JOIN V_CANAL_VENDAS B
  ON A.COD_EMPRESA=B.COD_EMPRESA
  AND A.ID_CLIFOR=B.ID_CLIENTE
  WHERE A.TIP_NF='S'
  GROUP BY A.COD_EMPRESA,B.NOME_GER

--SOLUÇÃO 2
SELECT A.COD_EMPRESA,B.NOME_GER,SUM(A.TOTAL_NF) AS TOTAL 
  FROM NOTA_FISCAL A
  INNER JOIN V_CANAL_VENDAS B
  ON A.COD_EMPRESA=B.COD_EMPRESA
  AND A.ID_CLIFOR=B.ID_CLIENTE
  WHERE A.TIP_NF='S'
  GROUP BY  ROLLUP (A.COD_EMPRESA,B.NOME_GER )
