/*10.	Performance de vendas por Vendedor


##### TABELAS PARA VIEW   #####
#                             #   
# CLIENTES                    #   
# CANAL_VENDAS_V_C            #   
# CANAL_VENDAS_G_V            #
# FUNCIONARIOS                #   
#                             #   
###############################

##### TABELAS ENVOLVIDAS  #####
#                             #   
# NOTA_FISCAL                 #   
# v_CANAL_VENDAS              #   
#                             #   
###############################
 */
 --CRIAÇÃO DA VIEW

  CREATE VIEW V_CANAL_VENDAS
  AS
 SELECT A.COD_EMPRESA,A.ID_CLIENTE,A.RAZAO_CLIENTE NOME_CLIENTE,B.MATRICULA_VEND,C.NOME NOME_VEND,D.MATRICULA_GER,E.NOME NOME_GER
   FROM CLIENTES A
     INNER JOIN CANAL_VENDAS_V_C B
	   ON A.COD_EMPRESA=B.COD_EMPRESA
	    AND A.ID_CLIENTE=B.ID_CLIENTE
	INNER JOIN FUNCIONARIO C
	  ON A.COD_EMPRESA=C.COD_EMPRESA
	    AND B.MATRICULA_VEND=C.MATRICULA
	INNER JOIN CANAL_VENDAS_G_V D
	  ON A.COD_EMPRESA=D.COD_EMPRESA
	    AND B.MATRICULA_VEND=D.MATRICULA_VEND
    INNER JOIN FUNCIONARIO E
	   ON A.COD_EMPRESA=E.COD_EMPRESA
	   AND D.MATRICULA_GER=E.MATRICULA


--VERFICANDO INCONSISTENCIA
SELECT * FROM CANAL_VENDAS_G_V

--INSERIR OS DADOS
	INSERT INTO CANAL_VENDAS_G_V VALUES ('2','7','8')
	INSERT INTO CANAL_VENDAS_G_V VALUES ('2','7','9')

-- GERAR  PERFOR VENDAS VENDEDOR


SELECT B.NOME_VEND,SUM(A.TOTAL_NF) AS TOTAL
  FROM NOTA_FISCAL A
  INNER JOIN V_CANAL_VENDAS B
  ON A.COD_EMPRESA=B.COD_EMPRESA
  AND A.ID_CLIFOR=B.ID_CLIENTE
  WHERE A.TIP_NF='S'
  GROUP BY B.NOME_VEND
  ORDER  BY 2 DESC

  --SOLUCAO 2

  
SELECT ISNULL(B.NOME_VEND,'TOTAL') AS VENDEDOR,SUM(A.TOTAL_NF) AS TOTAL
  FROM NOTA_FISCAL A
  INNER JOIN V_CANAL_VENDAS B
  ON A.COD_EMPRESA=B.COD_EMPRESA
  AND A.ID_CLIFOR=B.ID_CLIENTE
  WHERE A.TIP_NF='S'
  GROUP BY ROLLUP (B.NOME_VEND)
  ORDER  BY 2 ASC