/*21.	Valor acumulado e valor da última compra de cada cliente

##### TABELAS ENVOLVIDAS  #####
# NOTA_FISCAL                 #    
# CLIENTES                    #    
#                             #   
###############################

*/

--SOLUÇÃO 1

WITH T_MAX_VENDA (COD_EMPRESA,ID_CLIENTE,DATA_EMISSAO)
AS
(SELECT A.COD_EMPRESA,A.ID_CLIFOR,MAX(A.DATA_EMISSAO) DATA_EMISSAO
FROM NOTA_FISCAL A
 WHERE A.TIP_NF='S'
 GROUP BY A.COD_EMPRESA,A.ID_CLIFOR),

 T_ACUMULADO (COD_EMPRESA,ID_CLIENTE,VALOR_ACUM)
AS
(SELECT A.COD_EMPRESA,A.ID_CLIFOR,SUM(A.TOTAL_NF) AS TOTAL_ACUM
FROM NOTA_FISCAL A
 WHERE A.TIP_NF='S'
 GROUP BY A.COD_EMPRESA,A.ID_CLIFOR)

 SELECT A.COD_EMPRESA,
        A.NUM_NF,C.DATA_EMISSAO,
		C.ID_CLIENTE,
		B.RAZAO_CLIENTE,
		A.TOTAL_NF AS VAL_ULT_COMPRA, 
		D.VALOR_ACUM, 
		CAST(GETDATE()-C.DATA_EMISSAO AS INT) AS DIAS_SEM_COMPRA
 FROM NOTA_FISCAL A
  
 INNER JOIN CLIENTES B
 ON A.COD_EMPRESA=B.COD_EMPRESA
 AND A.ID_CLIFOR=B.ID_CLIENTE
 INNER JOIN T_MAX_VENDA C
  ON A.COD_EMPRESA=C.COD_EMPRESA
  AND A.DATA_EMISSAO=C.DATA_EMISSAO
  AND A.ID_CLIFOR=C.ID_CLIENTE
  INNER JOIN T_ACUMULADO D
  ON A.COD_EMPRESA=D.COD_EMPRESA
  AND A.ID_CLIFOR=D.ID_CLIENTE
 WHERE A.TIP_NF='S'
 ORDER BY 1,7 DESC


